apiVersion: promoter.argoproj.io/v1alpha1
kind: ArgoCDCommitStatus
metadata:
  name: argocdcommitstatus-demo
  namespace: argocd
spec:
  promotionStrategyRef:
    name: hydrator-demo
  applicationSelector:
    matchLabels:
      app: demo
