apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  annotations:
  name: hydrator-demo
  namespace: argocd
spec:
  activeCommitStatuses:
  - key: argocd-health
  environments:
  - branch: environments/development
    autoMerge: false
    sourceReferenceBranch: environments/development-next
  - branch: environments/staging
    sourceReferenceBranch: environments/staging-next
  - branch: environments/production
    sourceReferenceBranch: environments/production-next
    proposedCommitStatuses:
    - key: hcap
  gitRepositoryRef:
    name: hydrator-demo