apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: development:/Namespace:/development
    environment: development
    version: v1.0.1
  name: development
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: development:/Service:development/canary-demo
    environment: development
    version: v1.0.1
  name: canary-demo
  namespace: development
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: canary-demo
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: development:/Service:development/canary-demo-preview
    environment: development
    version: v1.0.1
  name: canary-demo-preview
  namespace: development
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: canary-demo
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: development:argoproj.io/Rollout:development/canary-demo
    environment: development
    version: v1.0.1
  labels:
    environment: development
  name: canary-demo
  namespace: development
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: canary-demo
  strategy:
    canary:
      canaryService: canary-demo-preview
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause:
            duration: 10
        - setWeight: 60
        - pause:
            duration: 10
        - setWeight: 80
        - pause:
            duration: 10
  template:
    metadata:
      labels:
        app: canary-demo
        environment: development
    spec:
      containers:
        - image: argoproj/rollouts-demo:green
          imagePullPolicy: Always
          name: canary-demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: development:networking.k8s.io/Ingress:development/canary-demo
    environment: development
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    version: v1.0.1
  name: canary-demo
  namespace: development
spec:
  rules:
    - host: canary.dev.argoproj.io
      http:
        paths:
          - backend:
              service:
                name: canary-demo
                port:
                  name: http
            path: /
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: development:networking.k8s.io/Ingress:development/canary-demo-preview
    environment: development
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    version: v1.0.1
  name: canary-demo-preview
  namespace: development
spec:
  rules:
    - host: canary-preview.dev.argoproj.io
      http:
        paths:
          - backend:
              service:
                name: canary-demo-preview
                port:
                  name: http
            path: /
            pathType: Prefix
