apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx-deployment.yaml
  - nginx-service.yaml
  - nginx.yaml

patches:
  - path: remove-ingress-demo.yaml
  - path: remove-ingress-demo-preview.yaml
  - path: rollout-steps.yaml

configurations:
  - transform.yaml

